var mongoose = require ('mongoose');

var craftSchema = mongoose.Schema({
  user: String,
  totalCost: {
    type: Number,
    default: 0
  },
  scrolls: {
    "Disarm": {name: String, amount: Number, cost: Number},
    "Light": {name: String, amount: Number, cost: Number},
    "Stone Bolt": {name: String, amount: Number, cost: Number},
    "Lightning Bolt": {name: String, amount: Number, cost: Number},
    "Magic Armor": {name: String, amount: Number, cost: Number},
    "Pin": {name: String, amount: Number, cost: Number},
    "Repel": {name: String, amount: Number, cost: Number},
    "Shield": {name: String, amount: Number, cost: Number},
    "Bind": {name: String, amount: Number, cost: Number},
    "Ice Bolt": {name: String, amount: Number, cost: Number},
    "Lesser Investment": {name: String, amount: Number, cost: Number},
    "Shatter": {name: String, amount: Number, cost: Number},
    "Wall of Force": {name: String, amount: Number, cost: Number},
    "Awaken": {name: String, amount: Number, cost: Number},
    "Flame Bolt": {name: String, amount: Number, cost: Number},
    "Shun": {name: String, amount: Number, cost: Number},
    "Release": {name: String, amount: Number, cost: Number},
    "Spell Shield": {name: String, amount: Number, cost: Number},
    "Stone Storm": {name: String, amount: Number, cost: Number},
    "Web": {name: String, amount: Number, cost: Number},
    "Elemental Shield": {name: String, amount: Number, cost: Number},
    "Lightning Storm": {name: String, amount: Number, cost: Number},
    "Sleep": {name: String, amount: Number, cost: Number},
    "Destroy": {name: String, amount: Number, cost: Number},
    "Ice Storm": {name: String, amount: Number, cost: Number},
    "Dispel": {name: String, amount: Number, cost: Number},
    "Dragon's Breath": {name: String, amount: Number, cost: Number},
    "Reflect Magic": {name: String, amount: Number, cost: Number},
    "Wizard Lock": {name: String, amount: Number, cost: Number}
  },
  potions: {
    "Cause Light Wounds": {name: String, amount: Number, cost: Number},
    "Cure Disease": {name: String, amount: Number, cost: Number},
    "Cure Light Wounds": {name: String, amount: Number, cost: Number},
    "Disease": {name: String, amount: Number, cost: Number},
    "Endow": {name: String, amount: Number, cost: Number},
    "Bless": {name: String, amount: Number, cost: Number},
    "Cause Wounds": {name: String, amount: Number, cost: Number},
    "Cure Wounds": {name: String, amount: Number, cost: Number},
    "Magic Armor": {name: String, amount: Number, cost: Number},
    "Remove Weakness": {name: String, amount: Number, cost: Number},
    "Weakness": {name: String, amount: Number, cost: Number},
    "Awaken": {name: String, amount: Number, cost: Number},
    "Cause Serious Wounds": {name: String, amount: Number, cost: Number},
    "Cure Serious Wounds": {name: String, amount: Number, cost: Number},
    "Remove Silence": {name: String, amount: Number, cost: Number},
    "Silence": {name: String, amount: Number, cost: Number},
    "Spell Shield": {name: String, amount: Number, cost: Number},
    "Cause Critical Wounds": {name: String, amount: Number, cost: Number},
    "Cure Critical Wounds": {name: String, amount: Number, cost: Number},
    "Elemental Shield": {name: String, amount: Number, cost: Number},
    "Restore": {name: String, amount: Number, cost: Number},
    "Sleep": {name: String, amount: Number, cost: Number},
    "Wither": {name: String, amount: Number, cost: Number},
    "Destruction": {name: String, amount: Number, cost: Number},
    "Remove Destruction": {name: String, amount: Number, cost: Number},
    "Cause Mortal Wounds": {name: String, amount: Number, cost: Number},
    "Cure Mortal Wounds": {name: String, amount: Number, cost: Number},
    "Drain": {name: String, amount: Number, cost: Number},
    "Purify": {name: String, amount: Number, cost: Number},
    "Remove Paralysis": {name: String, amount: Number, cost: Number},
    "Reflect Magic": {name: String, amount: Number, cost: Number}
  },
  weapons: {
    "Arrow": {name: String, amount: Number, cost: Number},
    "Bolt": {name: String, amount: Number, cost: Number},
    "Silvering an Arrow": {name: String, amount: Number, cost: Number},
    "Silvering a Bolt": {name: String, amount: Number, cost: Number},
    "Bludgeon": {name: String, amount: Number, cost: Number},
    "Dagger": {name: String, amount: Number, cost: Number},
    "Hatchet": {name: String, amount: Number, cost: Number},
    "Staff": {name: String, amount: Number, cost: Number},
    "Throwing Dagger": {name: String, amount: Number, cost: Number},
    "Javelin": {name: String, amount: Number, cost: Number},
    "Light Crossbow": {name: String, amount: Number, cost: Number},
    "Shield": {name: String, amount: Number, cost: Number},
    "Short Bow": {name: String, amount: Number, cost: Number},
    "Heavy Crossbow": {name: String, amount: Number, cost: Number},
    "Long Bow": {name: String, amount: Number, cost: Number},
    "Short Hammer": {name: String, amount: Number, cost: Number},
    "Short Mace": {name: String, amount: Number, cost: Number},
    "Silvering a Weapon": {name: String, amount: Number, cost: Number},
    "Spear": {name: String, amount: Number, cost: Number},
    "Long Hammer": {name: String, amount: Number, cost: Number},
    "Long Mace": {name: String, amount: Number, cost: Number},
    "Short Axe": {name: String, amount: Number, cost: Number},
    "Long Axe": {name: String, amount: Number, cost: Number},
    "Short Sword": {name: String, amount: Number, cost: Number},
    "Long Sword": {name: String, amount: Number, cost: Number},
    "Polearm": {name: String, amount: Number, cost: Number},
    "Two Handed Blunt": {name: String, amount: Number, cost: Number},
    "Two Handed Sword": {name: String, amount: Number, cost: Number},
    "Strengthening": {name: String, amount: Number, cost: Number}
  },
  alchemyContact: {
    "Alchemical Solvent": {name: String, amount: Number, cost: Number},
    "Liquid Light": {name: String, amount: Number, cost: Number},
    "Oil of Slipperiness": {name: String, amount: Number, cost: Number},
    "Paste of Stickiness": {name: String, amount: Number, cost: Number}
  },
  alchemyElixir: {
    "Cause Light Damage": {name: String, amount: Number, cost: Number},
    "Cure Light Damage": {name: String, amount: Number, cost: Number},
    "Intoxicate": {name: String, amount: Number, cost: Number},
    "Paranoia": {name: String, amount: Number, cost: Number},
    "Cause Damage": {name: String, amount: Number, cost: Number},
    "Hallucinate": {name: String, amount: Number, cost: Number},
    "Love": {name: String, amount: Number, cost: Number},
    "Weakness": {name: String, amount: Number, cost: Number},
    "Antidote": {name: String, amount: Number, cost: Number},
    "Cause Serious Damage": {name: String, amount: Number, cost: Number},
    "Laugh": {name: String, amount: Number, cost: Number},
    "Poison Shield": {name: String, amount: Number, cost: Number},
    "Nausea": {name: String, amount: Number, cost: Number},
    "Feeblemind": {name: String, amount: Number, cost: Number},
    "Sleep": {name: String, amount: Number, cost: Number},
    "Vertigo": {name: String, amount: Number, cost: Number},
    "Dominate": {name: String, amount: Number, cost: Number},
    "Paralysis": {name: String, amount: Number, cost: Number},
    "Amnesia": {name: String, amount: Number, cost: Number},
    "Berserk": {name: String, amount: Number, cost: Number},
    "Death": {name: String, amount: Number, cost: Number},
    "Enslavement Antidote": {name: String, amount: Number, cost: Number},
    "Euphoria Antidote": {name: String, amount: Number, cost: Number},
    "Love Potion #9": {name: String, amount: Number, cost: Number}
  },
  alchemyGas: {
    "Cause Light Damage": {name: String, amount: Number, cost: Number},
    "Paranoia": {name: String, amount: Number, cost: Number},
    "Cause Damage": {name: String, amount: Number, cost: Number},
    "Weakness": {name: String, amount: Number, cost: Number},
    "Cause Serious Damage": {name: String, amount: Number, cost: Number},
    "Laugh": {name: String, amount: Number, cost: Number},
    "Nausea": {name: String, amount: Number, cost: Number},
    "Feeblemind": {name: String, amount: Number, cost: Number},
    "Sleep": {name: String, amount: Number, cost: Number},
    "Vertigo": {name: String, amount: Number, cost: Number},
    "Dominate": {name: String, amount: Number, cost: Number},
    "Paralysis": {name: String, amount: Number, cost: Number}
  },
  alchemyWeapon: {
    "Paranoia": {name: String, amount: Number, cost: Number},
    "Vorpal Coating (Light)": {name: String, amount: Number, cost: Number},
    "Quicksilver": {name: String, amount: Number, cost: Number},
    "Vorpal Coating": {name: String, amount: Number, cost: Number},
    "Weakness": {name: String, amount: Number, cost: Number},
    "Laugh": {name: String, amount: Number, cost: Number},
    "Vorpal Coating (Serious)": {name: String, amount: Number, cost: Number},
    "Nausea": {name: String, amount: Number, cost: Number},
    "Feeblemind": {name: String, amount: Number, cost: Number},
    "Sleep": {name: String, amount: Number, cost: Number},
    "Vertigo": {name: String, amount: Number, cost: Number},
    "Dominate": {name: String, amount: Number, cost: Number}
  },
  trapsGas: {"Gas Trap": {name: String, amount: Number, cost: Number}},
  trapsNoisemaker: {"Noisemaker Trap": {name: String, amount: Number, cost: Number}},
  trapsWeapon: {
    "Weapon Trap: damage 2": {name: String, amount: Number, cost: Number},
    "Weapon Trap: damage 5": {name: String, amount: Number, cost: Number},
    "Weapon Trap: damage 10": {name: String, amount: Number, cost: Number},
    "Weapon Trap: damage 15": {name: String, amount: Number, cost: Number},
    "Weapon Trap: damage 20": {name: String, amount: Number, cost: Number},
    "Weapon Trap: damage 30": {name: String, amount: Number, cost: Number}
  },
  trapsFlameAcid: {
    "Flame/Acid Trap: damage 15": {name: String, amount: Number, cost: Number},
    "Flame/Acid Trap: damage 20": {name: String, amount: Number, cost: Number},
    "Flame/Acid Trap: damage 30": {name: String, amount: Number, cost: Number},
    "Flame/Acid Trap: damage 50": {name: String, amount: Number, cost: Number}
},
  trapsExplosive: {
    "Explosive Trap: damage 20": {name: String, amount: Number, cost: Number},
    "Explosive Trap: damage 30": {name: String, amount: Number, cost: Number},
    "Explosive Trap: damage 50": {name: String, amount: Number, cost: Number}
},
  trapsMechanical: {
    "Mechanical Trap: damage 20": {name: String, amount: Number, cost: Number},
    "Mechanical Trap: damage 30": {name: String, amount: Number, cost: Number},
    "Mechanical Trap: damage 50": {name: String, amount: Number, cost: Number},
    "Mechanical Trap: damage 100": {name: String, amount: Number, cost: Number}
  },
  armor: {
    "1 - 5 Armor Points": {name: String, amount: Number, cost: Number},
    "6 - 10 Armor Points": {name: String, amount: Number, cost: Number},
    "11 - 15 Armor Points": {name: String, amount: Number, cost: Number},
    "16 - 20 Armor Points": {name: String, amount: Number, cost: Number},
    "21 - 25 Armor Points": {name: String, amount: Number, cost: Number},
    "26 - 30 Armor Points": {name: String, amount: Number, cost: Number},
    "31 - 35 Armor Points": {name: String, amount: Number, cost: Number},
    "36 - 40 Armor Points": {name: String, amount: Number, cost: Number}
},
  hidden: Boolean
});

module.exports = mongoose.model('Craft', craftSchema);
